version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.18.2
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - '9090:9090'
    command:
      - '--config.file=/prometheus.yml'
    volumes:
      - '$PWD/dockerdata/prometheus.yml:/prometheus.yml'
      - '$PWD/dockerdata/discovered.json:/discovered.json:ro'

  promdiscovery:
    image: sgoroshko/promdiscovery
    restart: unless-stopped
    command:
      - 'compose'
      - '--debug'
      - '--output=/discovered.json'
      - '--key=metrics'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$PWD/dockerdata/discovered.json:/discovered.json'

  traefik:
    image: traefik:v2.2
    restart: unless-stopped
    deploy:
      resources:
        limits: { cpus: '1.00', memory: '50M' }
    expose:
      - 80
      - 443
      - 8080
    command:
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.metrics.address=:8080'
      - '--metrics.prometheus=true'
    labels:
      - 'metrics=:8080/metrics'
