version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.15.2
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - '9090:9090'
    command:
      - '--config.file=/prometheus.yml'
    volumes:
      - '$PWD/prometheus.yml:/prometheus.yml'
      - '$PWD/discovered.json:/discovered.json'

  promediscovery:
    image: sgoroshko/promdiscovery
    restart: unless-stopped
    command:
      - 'compose'
      - '--debug'
      - '--output=/discovered.json'
      - '--key=metrics'
#      - '--network=monitoring'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '$PWD/discovered.json:/discovered.json'

  traefik:
    image: traefik:v2.2
    restart: unless-stopped
    deploy:
      resources:
        limits: { cpus: '1.00', memory: '50M' }
    expose:
      - 80
      - 9090
    command:
      - '--entrypoints.web.address=:80'
      - '--entrypoints.metrics.address=:9090'
      - '--metrics.prometheus.entryPoint=metrics'
    labels:
      - 'metrics=9090'
