global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'compose'
    scrape_interval: 15s
    file_sd_configs:
      - files: [ '/discovered.json' ] # <- scraped targets
        refresh_interval: 30s
